### ISSUE TITLE
How to display the inserted data value in editor?

### ISSUE THREAD

**Issue by JohnHour89** [sumn2u/react-wysiwyg-typescript#2]
Hi, Sir, may how to get the value of the data after inserted the value to the db for display in wysiwyg editor?

**Comment by Jagatmachines** [comment]
Wysiwyg editor can be implemented as a controlled component using EditorState or un-controlled component using RawDraftContentState in order to get the data. Both of this result in JSON **String** data format.

```
// Example of a controlled component using EditorState

import Draft, { rawToDraft, draftToRaw } from 'react-wysiwyg-typescript';
import { EditorState } from 'draft-js';

const editorData = draftToRaw(EditorState.createEmpty()) //Create an empty editor instance
const editorState = rawToDraft(editorData)
let editorContent = '';

<Draft
 editorState={editorState}
 onEditorStateChange={(editorDataStore) => {
         //editorData is the JSON stringified data can be stored in data
         editorContent = editorDataStore
 }}
/>
```
**editorContent** will need to store in the database.
 



After the retrieval from the database
```
editorState = rawToDraft(editorContent)
<Draft
 editorState={editorState}
 onEditorStateChange={(editorDataStore) => {
         //editorData is the JSON stringified data can be stored in data
         editorContent = editorDataStore
 }}
/>
```

You can refer to https://jpuri.github.io/react-draft-wysiwyg/#/docs for more information

**Comment by sumn2u** [comment]
@JohnHour89  was it helpful?

**Comment by JohnHour89** [comment]
editorState = rawToDraft(editorContent)
<Draft
 editorState={editorState}
 onEditorStateChange={(editorDataStore) => {
         //editorData is the JSON stringified data can be stored in data
         editorContent = editorDataStore
 }}
/>

For this one I want to implement in another page so the "editorContent" is to be define like "let editorContent = ' ' " this??? If like this the value to be display in rich text editor is also empty.

**Comment by Jagatmachines** [comment]
if editorContent is an empty string or any other thing beside the JSON string required for Draft than before it reaches Draft component you will need to change it with

```
editorData = draftToRaw(EditorState.createEmpty()) //Create an empty editor instance
editorContent = rawToDraft(editorData)
```

**Comment by Jagatmachines** [comment]
as no further comments are presented we will be closing the issue
@sumn2u please close this issue

**Comment by sumn2u** [comment]
@Jagatmachines  sure thanks man
